@startuml VenteFormation

class Formation {
    -int id
    -string nom
    -text description
    -int duree_jours
    -double prix
}

class TypeFormation {
    -int id
    -string nom
}

class Categorie {
    -int id
    -string nom
}

Categorie "1" --> "0..n" Formation : catégorise
TypeFormation "0..n" -- "0..n" Formation : est de type

@enduml
