@startuml VenteFormation

class Formation
{
    -int id
    -string nom
    -text description
    -int duree_jours
    -boolean format
    -double prix
}

class Categorie
{
    -integer id
    -string nom
}

Categorie "1" --> "0..n" Formation : posséde >


@enduml
