@startuml venteFormation_use_case

left to right direction

actor Visiteur as v
actor Utilisateur as u

v <|-right- u

rectangle VenteFormation {
  usecase "Afficher les formations" as UC1
  usecase "Afficher les formations par catégorie" as UC2
  usecase "Afficher les formations contenant un mot clé" as UC3
  usecase "Afficher les formations selon le type de formation" as UC4
  usecase "Passer commande" as UC5
  usecase "Se connecter" as UC6
  usecase "S'inscrire" as UC7
}

v -- UC1
v -- UC7
u -- UC5

 UC2 .up.> UC1 : extends
 UC3 .up.> UC1 : extends
 UC4 .up.> UC1 : extends
 UC6 .up.> UC5 : include

@enduml